//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indextimetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int Id { get; set; }
        public string Ca_Học { get; set; }
        public string Thứ_Hai { get; set; }
        public string Thứ_Ba { get; set; }
        public string Thứ_Tư { get; set; }
        public string Thứ_Năm { get; set; }
        public string Thứ_Sáu { get; set; }
        public string Thứ_Bảy { get; set; }
    }
}
